name: export-and-branch-solution
# Export solution from DEV environment
#  unpack it and prepare, commit and push a git branch with the changes

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
env:
#edit your values here
  ENVIRONMENT_URL: 'https://rucarval.crm4.dynamics.com'
  CLIENT_ID: '21709150-affa-425c-aaca-be744f5587f1'
  TENANT_ID: '2a8ec2df-8e78-4b68-9c4f-fc4beca01fc9'

jobs:
  export-from-dev:
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true

    - name: who-am-i action
      uses: microsoft/powerplatform-actions/who-am-i@v0
      with:
        environment-url: ${{env.ENVIRONMENT_URL}}
        app-id: ${{env.CLIENT_ID}}
        client-secret: ${{ secrets.secret }}
        tenant-id: ${{env.TENANT_ID}}

    - name: export-solution action
      uses: microsoft/powerplatform-actions/export-solution@v0
      with:
        environment-url: ${{env.ENVIRONMENT_URL}}
        app-id: ${{env.CLIENT_ID}}
        client-secret: ${{ secrets.secret }}
        tenant-id: ${{env.TENANT_ID}}
        password-secret: ${{ secrets.secret }}
        solution-name: Layer2SecRoles
        solution-output-file: out/exported/Layer2SecRoles.zip

#    - name: unpack-solution action
#      uses: microsoft/powerplatform-actions/unpack-solution@v0
#      with:
#        solution-file: out/exported/ALMLab.zip
#        solution-folder: out/solutions/ALMLab
#        solution-type: 'Unmanaged'
#        overwrite-files: true

#    - name: branch-solution, prepare it for a PullRequest
#      uses: microsoft/powerplatform-actions/branch-solution@v0
#      with:
#        solution-folder: out/solutions/ALMLab
#        solution-target-folder: solutions/ALMLab
#        repo-token: ${{ secrets.GITHUB_TOKEN }}
#        allow-empty-commit: true
